[package]
name = "export_macro"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
syn = { version = "1.0.17", features = ["full"] }
quote = "1.0.3"
proc-macro2 = "1.0.9"
